# Generated by Django 2.2.23 on 2021-07-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneName',
            fields=[
                ('gene_name', models.CharField(max_length=30)),
                ('hgnc_id', models.CharField(max_length=30)),
                ('hotspot_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrCh38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomic_position_start_38', models.CharField(max_length=30)),
                ('genomic_position_end_38', models.CharField(max_length=40)),
                ('hotspot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots_database.GeneName')),
            ],
        ),
        migrations.CreateModel(
            name='GrCh37',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomic_position_start_37', models.CharField(max_length=30)),
                ('genomic_position_end_37', models.CharField(max_length=40)),
                ('hotspot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots_database.GeneName')),
            ],
        ),
    ]
