# Generated by Django 2.2.23 on 2021-06-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AminoAcidChange',
            fields=[
                ('codon_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=30)),
                ('amino_acid_position', models.CharField(max_length=30)),
                ('trinucleotides', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Codon',
            fields=[
                ('codon_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=30)),
                ('amino_acid_position', models.CharField(max_length=30)),
                ('trinucleotides', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgnc_id', models.CharField(max_length=30)),
                ('gene_name', models.CharField(max_length=30)),
                ('q_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspots',
            fields=[
                ('codon_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=30)),
                ('amino_acid_position', models.CharField(max_length=30)),
                ('genomic_position', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codon_position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots_database.Codon')),
            ],
        ),
    ]
