# Generated by Django 2.2.23 on 2021-07-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('chromosome_id', models.AutoField(primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeneName',
            fields=[
                ('gene_name', models.CharField(max_length=100)),
                ('hgnc_id', models.CharField(max_length=100)),
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrCh37',
            fields=[
                ('grch37_id', models.AutoField(primary_key=True, serialize=False)),
                ('genomic_position_start_37', models.CharField(max_length=100)),
                ('genomic_position_end_37', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrCh38',
            fields=[
                ('grch38_id', models.AutoField(primary_key=True, serialize=False)),
                ('genomic_position_start_38', models.CharField(max_length=100)),
                ('genomic_position_end_38', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspots',
            fields=[
                ('hotspot_id', models.AutoField(primary_key=True, serialize=False)),
                ('chromosome_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots_database.Chromosome')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots_database.GeneName')),
                ('grch37_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots_database.GrCh37')),
                ('grch38_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots_database.GrCh38')),
            ],
        ),
    ]
