# Generated by Django 2.2.23 on 2021-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genename',
            name='gene_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genename',
            name='hgnc_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grch37',
            name='genomic_position_end_37',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grch37',
            name='genomic_position_start_37',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grch38',
            name='genomic_position_end_38',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grch38',
            name='genomic_position_start_38',
            field=models.CharField(max_length=100),
        ),
    ]
